//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalendarz
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Klasa odpowiadaj¹ca tabeli z list¹ zadañ z bazy danych
    /// </summary>
    public partial class ListOfTasks
    {
        /// <summary>
        /// Nr identyfikacyjny zadania
        /// </summary>
        public int TaskId { get; set; }
        /// <summary>
        /// Opis zadania
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// Termin wykonania zadania
        /// </summary>
        public System.DateTime Date { get; set; }
    }
}
