//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalendarz
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Klasa odpowiadaj¹ca tabeli z list¹ wydarzeñ z bazy danych
    /// </summary>
    public partial class ListOfEvents
    {
        /// <summary>
        /// Nr identyfikacyjny wydarzenia
        /// </summary>
        public int EventId { get; set; }
        /// <summary>
        /// Opis wydarzenia
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// Data wydarzenia
        /// </summary>
        public System.DateTime Date { get; set; }
        /// <summary>
        /// Czas wydarzenia
        /// </summary>
        public Nullable<System.TimeSpan> Time { get; set; }
    }
}
